// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediathequeWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Adherents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adherents");
                });

            modelBuilder.Entity("Auteurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("Emprunts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdherentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateEmprunt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateRetourPrevue")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateRetourReelle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExemplaireId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdherentId");

                    b.HasIndex("ExemplaireId");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("Exemplaires", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OeuvreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OeuvreId");

                    b.ToTable("Exemplaires");
                });

            modelBuilder.Entity("Oeuvres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuteurId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuteursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuteursId");

                    b.ToTable("Oeuvres");
                });

            modelBuilder.Entity("Reservations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdherentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OeuvreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdherentId");

                    b.HasIndex("OeuvreId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Emprunts", b =>
                {
                    b.HasOne("Adherents", "Adherent")
                        .WithMany("Emprunts")
                        .HasForeignKey("AdherentId");

                    b.HasOne("Exemplaires", "Exemplaire")
                        .WithMany()
                        .HasForeignKey("ExemplaireId");

                    b.Navigation("Adherent");

                    b.Navigation("Exemplaire");
                });

            modelBuilder.Entity("Exemplaires", b =>
                {
                    b.HasOne("Oeuvres", "Oeuvre")
                        .WithMany()
                        .HasForeignKey("OeuvreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oeuvre");
                });

            modelBuilder.Entity("Oeuvres", b =>
                {
                    b.HasOne("Auteurs", "Auteurs")
                        .WithMany("Oeuvres")
                        .HasForeignKey("AuteursId");

                    b.Navigation("Auteurs");
                });

            modelBuilder.Entity("Reservations", b =>
                {
                    b.HasOne("Adherents", "Adherent")
                        .WithMany("Reservations")
                        .HasForeignKey("AdherentId");

                    b.HasOne("Oeuvres", "Oeuvre")
                        .WithMany()
                        .HasForeignKey("OeuvreId");

                    b.Navigation("Adherent");

                    b.Navigation("Oeuvre");
                });

            modelBuilder.Entity("Adherents", b =>
                {
                    b.Navigation("Emprunts");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Auteurs", b =>
                {
                    b.Navigation("Oeuvres");
                });
#pragma warning restore 612, 618
        }
    }
}
